Update dependency com.squareup.okhttp3:okhttp to v5 (#1001)
This PR contains the following updates:

| Package | Change | Age | Confidence |
|---|---|---|---|
| [com.squareup.okhttp3:okhttp](https://square.github.io/okhttp/)
([source](https://redirect.github.com/square/okhttp)) | `4.12.0` ->
`5.0.0` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/com.squareup.okhttp3:okhttp/5.0.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/com.squareup.okhttp3:okhttp/4.12.0/5.0.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

> [!WARNING]
> Some dependencies could not be looked up. Check the warning logs for
more information.

---

### Release Notes

<details>
<summary>square/okhttp (com.squareup.okhttp3:okhttp)</summary>

###
[`v5.0.0`](https://redirect.github.com/square/okhttp/blob/HEAD/CHANGELOG.md#Version-500)

*2025-07-02*

This is our first stable release of OkHttp since 2023. Here's the
highlights if you're upgrading
from OkHttp 4.x:

**OkHttp is now packaged as separate JVM and Android artifacts.** This
allows us to offer
platform-specific features and optimizations. If your build system
handles \[Gradle module metadata],
this change should be automatic.

**MockWebServer has a new coordinate and package name.** We didn’t like
that our old artifact
depends on JUnit 4 so the new one doesn’t. It also has a better API
built on immutable values. (We
intend to continue publishing the old `okhttp3.mockwebserver` artifact
so there’s no urgency to
migrate.)

| Coordinate | Package Name | Description |
|:-------------------------------------------------|
:-------------------- | :-------------------------------- |
| com.squareup.okhttp3:mockwebserver3:5.0.0 | mockwebserver3 | Core
module. No JUnit dependency! |
| com.squareup.okhttp3:mockwebserver3-junit4:5.0.0 |
mockwebserver3.junit4 | Optional JUnit 4 integration. |
| com.squareup.okhttp3:mockwebserver3-junit5:5.0.0 |
mockwebserver3.junit5 | Optional JUnit 5 integration. |
| com.squareup.okhttp3:mockwebserver:5.0.0 | okhttp3.mockwebserver |
Obsolete. Depends on JUnit 4. |

**OkHttp now supports Happy Eyeballs (\[RFC 8305]\[rfc\_8305]) for
IPv4+IPv6 networks.** It attempts
both IPv6 and IPv4 connections concurrently, keeping whichever connects
first.

**We’ve improved our Kotlin APIs.** You can skip the builder:

```kotlin
val request = Request(
  url = "https://cash.app/".toHttpUrl(),
)
```

**OkHttp now supports \[GraalVM].**

Here’s what has changed since 5.0.0-alpha.17:

- Upgrade: \[Okio 3.15.0]\[okio\_3\_15\_0].
- Upgrade: \[Kotlin 2.2.0]\[kotlin\_2\_2\_0].
- Fix: Don't crash with a `NoSuchMethodError` when using OkHttp with the
Sentry SDK.
- Fix: Retain the query data in the old
`okhttp3.mockwebserver.RecordedRequest.path` property. We
inadvertently changed this behavior when we introduced the
`mockwebserver3` API.

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Renovate
Bot](https://redirect.github.com/renovatebot/renovate).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS4xNy4yIiwidXBkYXRlZEluVmVyIjoiNDEuMTcuMiIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOlsidXBkYXRlLW1ham9yIl19-->

Co-authored-by: grafanarenovatebot[bot] <146220760+grafanarenovatebot[bot]@users.noreply.github.com>